# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
# deleteDatasources:

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: InfluxDB Metrics DB
    type: influxdb
    url: http://influx-service:8086
    database: influx_metrics_db
    user: user
    secureJsonData:
      password: pass
  - name: NGINX Metrics DB
    type: influxdb
    url: http://influx-service:8086
    database: nginx_metrics_db
    user: user
    secureJsonData:
      password: pass
  - name: phpMyAdmin Metrics DB
    type: influxdb
    url: http://influx-service:8086
    database: phpmyadmin_metrics_db
    user: user
    secureJsonData:
      password: pass
  - name: WordPress Metrics DB
    type: influxdb
    url: http://influx-service:8086
    database: wordpress_metrics_db
    user: user
    secureJsonData:
      password: pass
  - name: MySQL Metrics DB
    type: influxdb
    url: http://influx-service:8086
    database: mysql_metrics_db
    user: user
    secureJsonData:
      password: pass
  - name: FTPS Metrics DB
    type: influxdb
    url: http://influx-service:8086
    database: ftps_metrics_db
    user: user
    secureJsonData:
      password: pass
  - name: Grafana Metrics DB
    type: influxdb
    url: http://influx-service:8086
    database: grafana_metrics_db
    user: user
    secureJsonData:
      password: pass

