apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - name: login
          containerPort: 21
        - name: data
          containerPort: 30021
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations: 
    metallb.universe.tf/allow-shared-ip: sharing-key
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.64.21
  ports:
  - name: login
    protocol: TCP
    port: 21
    targetPort: 21
  - name: data
    protocol: TCP
    port: 30021
    targetPort: 30021
